# Generated by Django 3.2.5 on 2021-08-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAuthentication',
        ),
    ]
