# Generated by Django 3.2.5 on 2021-08-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    managed = False

    dependencies = [
        ('authentication', '0002_delete_userauthentication'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
